CREATE TABLE BOOK (
ISBN VARCHAR(30) NOT NULL UNIQUE, 
AUTHOR VARCHAR(30),
TITLE VARCHAR(30) NOT NULL UNIQUE,
PUBLISHER_NAME VARCHAR(30),
PUBLICATION_YEAR YEAR,
CATEGORY VARCHAR(30),
SELLING_PRICE FLOAT,
THRESHOLD INT,
COPIES INT,
PRIMARY KEY(ISBN, TITLE),
FOREIGN KEY (PUBLISHER_NAME) REFERENCES PUBLISHER (PUBLISHER_NAME) ON UPDATE CASCADE ON DELETE CASCADE
);


