DROP SCHEMA IF EXISTS BOOK_STORE;
CREATE SCHEMA BOOK_STORE;
USE BOOK_STORE;

CREATE TABLE PUBLISHER (
PUBLISHER_NAME VARCHAR (30) PRIMARY KEY NOT NULL UNIQUE,
ADDRESS VARCHAR(30),
PHONE VARCHAR(30)
);