CREATE TABLE SALES (
	ISBN VARCHAR(30) NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	DATE_ORDERED DATE NOT NULL,
	USER_NAME VARCHAR(30) NOT NULL,
	COPIES INT NOT NULL,
	FOREIGN KEY (ISBN) REFERENCES BOOK (ISBN) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (TITLE) REFERENCES BOOK (TITLE) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_NAME) REFERENCES ONLINE_USER(USER_NAME) ON UPDATE CASCADE ON DELETE CASCADE
);